//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public string Clave_Genero { get; set; }
        public string Clave_Pasillo { get; set; }
        public string Clave_Libro { get; set; }
        public string Autor_Libro { get; set; }
        public string Titulo_Libro { get; set; }
        public System.DateTime Fecha_Publicacion { get; set; }
        public string Estado { get; set; }
    }
}
