//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosLibreria
    {
        public string Nombre_Usuario { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public string Folio_Credencial { get; set; }
    }
}
